FROM ubuntu

RUN apt update
RUN apt install python3-pip -y
RUN pip3 install Flask
RUN apt install curl -y
WORKDIR /app

COPY . .
# Syntax depends on the service you are running
HEALTHCHECK --interval=3s --timeout=30s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:5000/health || exit 1

CMD ["python3","-m","flask","run","--host=0.0.0.0"]
